### ISSUE TITLE
Low res images

### ISSUE THREAD

**Issue by liviatronic** [hard-g/acd#1]
URL: https://hardg.com/acd/
Issue: Images in lightbox are low res and cropped, expecting to see higher res and uncropped
<img width="1042" alt="Screen Shot 2022-09-16 at 5 54 14 PM" src="https://user-images.githubusercontent.com/33435482/190805431-69f05677-7029-41a1-9475-a9b936fc29cd.png">

**Comment by boonebgorges** [comment]
Thanks for flagging this. I have done a review and swapped out for proper images, as appropriate.

As part of these changes (and part of the promised improvements in performance) I changed some of the internals of the overlay, so that the full-resolution image that's used for zooming is only loaded when you click through to the image. This allows us to keep the initial pageload pretty slim.
