### ISSUE TITLE
'Documents' thumbnail styling

### ISSUE THREAD

**Issue by liviatronic** [hard-g/acd#11]
Not a functionality issue, but flagging a few styling differences:<br>

1. On test site, document thumbnails are cropped to square size, while on production site they are full height and variable width based on original document size.
2. On test site, document thumbnails appear very low res.
3. On test site, gray background ends at the top of `featured-documents`, while on production site it extends up to the top of `documents-container`
<br>
Test site:<br>
<img width="1430" alt="Screen Shot 2022-09-25 at 11 26 55 AM" src="https://user-images.githubusercontent.com/33435482/192151702-db9500d1-eb1d-4fa6-ae8a-080e755428b3.png"><br>
Production site:<br>
<img width="1431" alt="Screen Shot 2022-09-25 at 11 26 47 AM" src="https://user-images.githubusercontent.com/33435482/192151716-951a5cbe-7fec-4bcc-a4f4-415d6a79098d.png">

**Comment by boonebgorges** [comment]
Thanks for the screenshots. I'd been a bit aggressive in my performance tuning. I've changed the behavior of this page so that a larger crop size is used - still far faster than production, but not grainy, and it respecting the aspect ratio of the original.

> On test site, gray background ends at the top of featured-documents, while on production site it extends up to the top of documents-container

I took two minutes to try to understand why this differs on production but I couldn't figure it out, so I wrote my own version of the relevant CSS :-D
