### ISSUE TITLE
Editing text at end of footnote starts a new paragraph

### ISSUE THREAD

**Issue by liviatronic** [hard-g/acd#20]
This can be worked around, but thought I'd flag it in case there's an easy-ish fix. When I try to edit text at the end of the footnote (in the example, adding a period), a new paragraph is started instead.
<img width="866" alt="Screenshot 2022-11-10 at 2 12 45 PM" src="https://user-images.githubusercontent.com/33435482/201187495-3844c7a7-da39-4c88-9084-cce5cb8f1f6d.png">

**Comment by boonebgorges** [comment]
Here's another case, like #21, where we're dealing with the fact that 'footnote' is a format rather than a block. My best suggestion is to establish an editorial practice of always clicking near the end of the footnote - but not at the actual end - and then using the arrow keys to navigate to the end before typing. See below:

![Peek 2022-11-10 15-55](https://user-images.githubusercontent.com/246627/201213721-701d3743-e4b0-4363-aa33-e4a732382875.gif)

It's helpful to notice that the "caret" menu will be highlighted, and the background of the footnote will be shaded pink, when the cursor is inside the delimiters of the footnote. So this should indicate whether it's "safe" to begin typing.

**Comment by liviatronic** [comment]
Yep, all makes sense.
