### ISSUE TITLE
Deleting footnotes

### ISSUE THREAD

**Issue by liviatronic** [hard-g/acd#21]
Adding footnotes works perfectly! But when I delete it, the text is deleted within the visual block editor, but the markup remains, and an empty footnote remains on the site. Easy to fix by editing HTML, but ideally that wouldn't be necessary for ease of editing?
<img width="871" alt="Screenshot 2022-11-10 at 2 34 02 PM" src="https://user-images.githubusercontent.com/33435482/201189664-c3eaa7ba-81ac-4e41-955c-055e11cacfe0.png">

**Comment by boonebgorges** [comment]
Yes, unfortunately the deletion process is a bit finicky. It's a byproduct of the fact that I'm using the block editor's "formatting" tool rather than a proper block (which would have a proper delete button).

I can't really add a button or anything that would make it foolproof. But I have two suggestions for editorial workflow that should help make this mostly a non-problem.

1. Remove the 'footnote' styling before deletion. When you click into the footnote, you'll see the "caret" menu highlighted. Click into it and toggle 'Footnote'. (Basically, you're reversing the process of creating a footnote.) Then delete the text. Like this:

![Peek 2022-11-10 15-49](https://user-images.githubusercontent.com/246627/201212826-6ccfd993-c004-47fb-8b25-f4936a5d1831.gif)

2. If you ensure that the cursor is past the boundary of the footnote before you start deleting, WP will remove the entire element. The most surefire way to do this is to start with the cursor at the beginning of the paragraph or sentence that follows the footnote. Then, you can backspace the whole thing. Like this:

![Peek 2022-11-10 15-52](https://user-images.githubusercontent.com/246627/201213254-7e1bee83-725e-4f2e-a957-4ef7d3589d7d.gif)

Play with these two options and see which of them feels natural to you and to Riv-Ellen. Then, be sure to document it.

**Comment by liviatronic** [comment]
This all totally makes sense, thanks!
