### ISSUE TITLE
Attribution block - Eliminate automatic italics for attribution title

### ISSUE THREAD

**Issue by liviatronic** [hard-g/acd#23]
Unless I'm mistaken, it looks like attribution titles are automatically italicized (which actually means non-italicized in this context lol). Unfortunately this won't work, since it's likely that we'll be adding attributions that are not from a book. This is a high priority—we'll have to italicize book titles manually as needed, so that the block can accommodate a wider range of media.

<img width="322" alt="Screenshot 2022-11-29 at 1 04 16 PM" src="https://user-images.githubusercontent.com/33435482/204613912-5b25755e-271a-44ef-81ab-34174fb9bdff.png">

**Comment by boonebgorges** [comment]
Yes, the italicization "flip" is an artifact of the way the theme previously worked.

I've made a change so that no italicization is forced. This means that you'll need to manually apply italics where they're needed. Compare the first quote from Eric Sevareid at https://hardg.com/acd/essay/student-activism-in-context-of-1930s/ and on production https://acampusdivided.umn.edu/essay/student-activism-in-context-of-1930s/ Ideally we'd wait until after the relaunch to go through and correct these italics, to avoid any more divergence of content on the staging site. Let me know what you think.

**Comment by liviatronic** [comment]
Thanks for making this change. Sounds good, we can correct it after
relaunch.

Livia Foldes <http://liviafoldes.com/> (she/her)
-------------------------
***@***.***
(415) 812-0707
-------------------------
(●*∩_∩*●)
